utils::globalVariables(
    c(
        "maintainer",
        "Repository",
        "Package",
        "Version",
        "GithubUsername",
        "GithubSHA1",
        "install_cmd",
        "."
    )
)
